In [14]:
from scipy.stats import chi2_contingency
import numpy as np
g, p, dof, expctd = chi2_contingency(obs)

In [13]:
obs=np.array([[100,50,40], [150,30,60],[250,80,100]])
g, p, dof, expctd = chi2_contingency(obs)
print(g,p,dof)
print(expctd)

13.366776315789476 0.009615993841544308 4
[[110.46511628  35.34883721  44.18604651]
 [139.53488372  44.65116279  55.81395349]
 [250.          80.         100.        ]]


In [10]:
obs = np.array([[100,150,250], [50,30,80],[40,60,100]])
g, p, dof, expctd = chi2_contingency(obs)
print(g,p,dof)
print(expctd)

(13.366776315789474,
 0.009615993841544313,
 4,
 array([[110.46511628, 139.53488372, 250.        ],
        [ 35.34883721,  44.65116279,  80.        ],
        [ 44.18604651,  55.81395349, 100.        ]]))

In [11]:
obs = np.array([[100,150], [50,30],[40,60]])
g, p, dof, expctd = chi2_contingency(obs)
print(g,p,dof)
print(expctd)

(13.366776315789473,
 0.0012515303983001058,
 2,
 array([[110.46511628, 139.53488372],
        [ 35.34883721,  44.65116279],
        [ 44.18604651,  55.81395349]]))

In [3]:
obs=np.array([[200,190,390],[200,210,410]])
g, p, dof, expctd = chi2_contingency(obs)
print(g,p,dof)
print(expctd)

(0.5003126954346466, 0.7786790288649662, 2)

In [4]:
obs=np.array([[20,25,45],[22,22,44],[18,35,53]])
g, p, dof, expctd = chi2_contingency(obs)
print(g,p,dof)
print(expctd)

(2.6638765318470803, 0.6155503887287381, 4)

In [5]:
obs=np.array([[200  ,190,390],[200,210,410],[400,400,800]])
g, p, dof, expctd = chi2_contingency(obs)
print(g,p,dof)
print(expctd)

(0.5003126954346466, 0.9734705307698983, 4)

In [ ]:
obs=np.array([[200,190,390],[200,210,410],[400,400,800]])
chi2_contingency(obs)
g, p, dof, expctd = chi2_contingency(obs)
print(g,p,dof)
print(expctd)

In [5]:
obs = np.array([[100,50,40,190 ], [150,30,60,240],[250,80,100,430]])
g, p, dof, expctd = chi2_contingency(obs)
print(g,p,dof)
print(expctd)

(13.366776315789474, 0.037567471803405195, 6)